/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis;

import java.nio.file.Paths;
import java.util.List;

public class App {
    public static void main(String[] args) {
        Lexer lexer = new ConcreteLexer();
        List<Token> sentences = lexer.scan(Paths.get("test.txt"));

        System.out.println(sentences.toString());
    }
}
